// Stylesheets for the generated pages. The website's tokens match docs/index.html; the Help Book's are its own,
// since the Help Viewer shows pages without the site's navigation.

/// Shared by both outputs: the article's prose, tables, code and callouts.
private let prose = """
article{font:18px/1.65 var(--prose);color:var(--ink)}
article h1,article h2,article h3{font-family:var(--prose);line-height:1.15;letter-spacing:-.01em;text-wrap:balance}
article h1{font-size:clamp(34px,5vw,46px);font-weight:700;margin:0 0 18px}
article h2{font-size:28px;font-weight:700;margin:44px 0 12px}
article h3{font-size:21px;font-weight:600;margin:30px 0 8px}
article p,article ul,article ol,article pre,article .table,article .callout,article blockquote{margin:0 0 16px}
article ul,article ol{padding-left:1.4em}
article li{margin:4px 0}
article a{color:var(--accent);text-decoration:underline;text-decoration-thickness:1px;text-underline-offset:3px}
article a:hover{text-decoration-thickness:2px}
article code{font:.84em var(--mono);background:var(--field);padding:1px 6px;border-radius:6px}
article pre{background:var(--code);border-radius:12px;padding:14px 18px;overflow-x:auto;position:relative}
article pre code{background:none;padding:0;font-size:14px;line-height:1.55}
article .code-label{position:absolute;top:6px;right:12px;font:600 11px var(--ui);color:var(--ink2)}
article img{max-width:100%;height:auto;border-radius:12px}
article .table{overflow-x:auto}
article table{border-collapse:collapse;font:15px/1.45 var(--ui);min-width:60%}
article th,article td{text-align:left;padding:9px 14px;border-bottom:1px solid var(--rule);vertical-align:top}
article th{font-weight:600;border-bottom-width:2px}
article blockquote{padding-left:16px;border-left:3px solid var(--rule);color:var(--ink2)}
article .callout{--c:var(--accent);padding:12px 18px;border-radius:12px;border-left:3px solid var(--c);background:color-mix(in srgb,var(--c) 9%,transparent);font-size:16.5px}
article .callout-tip{--c:var(--tip)}article .callout-warning{--c:var(--warning)}article .callout-important{--c:var(--important)}
article .callout>:last-child{margin-bottom:0}
article .callout-title{font:600 12.5px var(--ui);color:var(--c);margin-bottom:4px}
article .license{font:14.5px/1.6 var(--ui);color:var(--ink2);padding:18px 22px;border:1px solid var(--rule);border-radius:14px;margin-bottom:16px}
article .license h3{font:600 13px var(--ui);color:var(--ink);letter-spacing:.02em;margin:14px 0 6px}
article .license h3:first-child{margin-top:0}
article .license p,article .license ul{margin:0 0 10px}
article .license hr{border:0;border-top:1px solid var(--rule);margin:16px 0}
.topics{list-style:none;padding:0!important;display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}
.topics li{margin:0}
.topics a{display:block;height:100%;padding:16px 18px;border-radius:16px;border:1px solid var(--rule);text-decoration:none!important;color:var(--ink)}
.topics a:hover{background:var(--field)}
.topics strong{display:block;font:600 16px var(--ui);color:var(--accent);margin-bottom:4px}
.topics span{display:block;font:14px/1.5 var(--ui);color:var(--ink2)}
.visually-hidden{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
"""

let pagesCSS = """
/* Generated by Tools/HelpBuilder from help/*.md. Edit the builder, not this file. */
:root{
  --page:#F7F5F0;--page2:#EFECE5;--ink:#16161A;--ink2:#55555D;--ink3:#8C8B92;
  --rule:rgba(0,0,0,.12);--field:rgba(0,0,0,.05);--code:#F3F1ED;
  --accent:#0A64D6;--accentSoft:rgba(10,100,214,.13);--tip:#1E7B34;--warning:#B53000;--important:#7E3BA1;
  --glass:rgba(255,255,255,.72);
  --glassEdge:0 0 0 .5px rgba(0,0,0,.09),0 6px 20px rgba(0,0,0,.08),inset 0 1px 0 rgba(255,255,255,.95);
  --prose:ui-serif,"New York","Newsreader","Iowan Old Style",Georgia,serif;
  --ui:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Inter,system-ui,sans-serif;
  --mono:ui-monospace,"SF Mono","JetBrains Mono",Menlo,monospace;
  color-scheme:light dark;
}
/* The site's appearance follows macOS unless a visitor picks one (assets/site.js sets data-theme). */
@media (prefers-color-scheme: dark){
  :root:not([data-theme="light"]){
    --page:#0C0C0E;--page2:#121215;--ink:#F3F2EE;--ink2:#AEAEB2;--ink3:#8E8E93;
    --rule:rgba(255,255,255,.14);--field:rgba(255,255,255,.07);--code:#1E1E23;
    --accent:#5A9DFF;--accentSoft:rgba(61,139,255,.2);--tip:#4CD964;--warning:#FF9F0A;--important:#DA8FFF;
    --glass:rgba(30,30,36,.62);
    --glassEdge:0 0 0 .5px rgba(255,255,255,.12),0 8px 28px -8px rgba(0,0,0,.5),inset 0 1px 0 rgba(255,255,255,.07);
    color-scheme:dark;
  }
}
:root[data-theme="dark"]{
    --page:#0C0C0E;--page2:#121215;--ink:#F3F2EE;--ink2:#AEAEB2;--ink3:#8E8E93;
    --rule:rgba(255,255,255,.14);--field:rgba(255,255,255,.07);--code:#1E1E23;
    --accent:#5A9DFF;--accentSoft:rgba(61,139,255,.2);--tip:#4CD964;--warning:#FF9F0A;--important:#DA8FFF;
    --glass:rgba(30,30,36,.62);
    --glassEdge:0 0 0 .5px rgba(255,255,255,.12),0 8px 28px -8px rgba(0,0,0,.5),inset 0 1px 0 rgba(255,255,255,.07);
    color-scheme:dark;
}
:root[data-theme="light"]{color-scheme:light}
*{box-sizing:border-box;margin:0;padding:0}
html{-webkit-text-size-adjust:100%}
body{background:var(--page);color:var(--ink);font:16px/1.6 var(--ui);-webkit-font-smoothing:antialiased}
a{color:var(--accent)}
:focus-visible{outline:3px solid var(--accent);outline-offset:2px;border-radius:6px}
.skip{position:absolute;left:12px;top:-60px;z-index:100;padding:10px 16px;border-radius:10px;background:var(--accent);color:#fff;font-weight:600;text-decoration:none}
.skip:focus{top:12px}
.wrap{max-width:1120px;margin:0 auto;padding:0 24px}
.glass{background:var(--glass);-webkit-backdrop-filter:blur(20px) saturate(180%);backdrop-filter:blur(20px) saturate(180%);box-shadow:var(--glassEdge)}
.nav{position:sticky;top:12px;z-index:50;max-width:1120px;margin:12px auto 0;padding:0 12px}
.cap{display:flex;align-items:center;gap:2px;height:44px;padding:4px;border-radius:999px;width:max-content;max-width:100%}
.brand{display:flex;align-items:center;gap:10px;padding:0 14px 0 6px;font:600 15px var(--ui);color:var(--ink);text-decoration:none}
.brand img{width:30px;height:30px;border-radius:8px}
.cap a.link{padding:0 14px;height:36px;display:flex;align-items:center;border-radius:999px;font-size:14px;color:var(--ink);text-decoration:none}
.cap a.link:hover,.cap a.link[aria-current]{background:var(--field)}
.btn{display:inline-flex;align-items:center;height:36px;padding:0 16px;border-radius:999px;font:600 14px var(--ui);text-decoration:none}
.btn-accent{background:#0A64D6;color:#fff}
@media (max-width:620px){.cap a.hide-s{display:none}}
.theme-btn{display:none;width:36px;height:36px;border:0;border-radius:50%;background:transparent;color:var(--ink);cursor:pointer;place-items:center}
.js .theme-btn{display:grid}
.theme-btn:hover{background:var(--field)}
.theme-btn svg{width:18px;height:18px}
.theme-btn .sun{display:none}
[data-resolved="dark"] .theme-btn .sun{display:block}
[data-resolved="dark"] .theme-btn .moon{display:none}
::view-transition-old(root),::view-transition-new(root){animation:none;mix-blend-mode:normal}
.layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:56px;padding-top:56px;padding-bottom:96px}
.toc{position:sticky;top:84px;align-self:start;max-height:calc(100vh - 100px);overflow:auto;font-size:14.5px}
.toc-title{font:600 12px var(--ui);letter-spacing:.06em;text-transform:uppercase;margin-bottom:10px}
.toc-title a{color:var(--ink2);text-decoration:none}
.toc ul{list-style:none;display:grid;gap:2px}
.toc li a{display:block;padding:6px 12px;border-radius:10px;color:var(--ink);text-decoration:none}
.toc li a:hover{background:var(--field)}
.toc li a[aria-current="page"]{background:var(--accentSoft);color:var(--ink);font-weight:600;box-shadow:inset 3px 0 0 var(--accent)}
main{max-width:720px;outline:none}
.crumbs ol{list-style:none;display:flex;flex-wrap:wrap;gap:6px;font-size:13.5px;color:var(--ink2);margin-bottom:22px}
.crumbs li+li::before{content:"›";margin-right:6px;color:var(--ink3)}
.crumbs a{color:var(--ink2)}
\(prose)
article kbd{font:600 .8em var(--ui);padding:2px 7px;border-radius:6px;background:var(--field);box-shadow:inset 0 -1px 0 var(--rule)}
.search{margin:28px 0 20px}
.search label{display:block;font:600 14px var(--ui);margin-bottom:6px}
.search input{width:100%;height:44px;padding:0 16px;border-radius:12px;border:1px solid var(--rule);background:var(--page);color:var(--ink);font:16px var(--ui)}
.search .count{font:14px var(--ui);color:var(--ink2);margin-top:8px;min-height:1.5em}
.edit{margin-top:40px!important;font:13.5px var(--ui)!important;color:var(--ink2)}
.pager{display:flex;justify-content:space-between;gap:12px;margin-top:40px;padding-top:24px;border-top:1px solid var(--rule)}
.pager a{display:flex;flex-direction:column;padding:12px 16px;border-radius:14px;border:1px solid var(--rule);text-decoration:none;color:var(--accent);font-weight:600;max-width:48%}
.pager a[rel=next]{text-align:right;margin-left:auto}
.pager a span{font:500 12.5px var(--ui);color:var(--ink2)}
.pager a:hover{background:var(--field)}
footer{border-top:1px solid var(--rule);padding:34px 0 48px;font-size:13.5px;color:var(--ink2)}
footer .wrap{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}
footer nav{display:flex;gap:8px 20px;flex-wrap:wrap}
footer a{color:var(--ink2)}
@media (max-width:860px){
  .layout{grid-template-columns:minmax(0,1fr);gap:40px;padding-top:36px}
  .toc{position:static;max-height:none;order:2;border-top:1px solid var(--rule);padding-top:24px}
}
@media (max-width:560px){.wrap{padding:0 16px}article{font-size:17px}}
@media (prefers-reduced-motion: reduce){*{transition:none!important;scroll-behavior:auto!important}}
@media print{.nav,.toc,.pager,footer,.skip,.search{display:none}.layout{display:block;padding:0}}

"""

let helpCSS = """
/* Generated by Tools/HelpBuilder from help/*.md. Edit the builder, not this file. */
:root{
  --page:#FFFFFF;--ink:#1D1D1F;--ink2:#5E5E63;--rule:rgba(0,0,0,.12);--field:rgba(0,0,0,.05);--code:#F3F1ED;
  --accent:#0A64D6;--tip:#1E7B34;--warning:#B53000;--important:#7E3BA1;
  --prose:ui-serif,"New York",Georgia,serif;--ui:-apple-system,system-ui,sans-serif;--mono:ui-monospace,"SF Mono",Menlo,monospace;
  color-scheme:light dark;
}
@media (prefers-color-scheme: dark){
  :root{--page:#1E1E20;--ink:#F2F2F7;--ink2:#AEAEB2;--rule:rgba(255,255,255,.16);--field:rgba(255,255,255,.08);--code:#2A2A2D;
    --accent:#5A9DFF;--tip:#4CD964;--warning:#FF9F0A;--important:#DA8FFF}
}
*{box-sizing:border-box}
body{margin:0;background:var(--page);color:var(--ink);font:15px/1.55 var(--ui);-webkit-font-smoothing:antialiased;padding:22px 28px 30px}
main{max-width:680px}
.crumbs{font-size:13px;margin-bottom:14px}
.crumbs a{color:var(--ink2);text-decoration:none}
\(prose)
article,main{font:16.5px/1.6 var(--prose)}
main h1{font:700 30px/1.15 var(--prose);margin:0 0 14px}
main h2{font:700 22px/1.2 var(--prose);margin:32px 0 10px}
main h3{font:600 18px/1.25 var(--prose);margin:24px 0 6px}
main p,main ul,main ol,main pre,main .table,main .callout,main blockquote{margin:0 0 14px}
main a{color:var(--accent)}
main code{font:.84em var(--mono);background:var(--field);padding:1px 5px;border-radius:5px}
main pre{background:var(--code);border-radius:10px;padding:12px 16px;overflow-x:auto;position:relative}
main pre code{background:none;padding:0}
main .code-label{position:absolute;top:5px;right:10px;font:600 10.5px var(--ui);color:var(--ink2)}
main table{border-collapse:collapse;font:13.5px/1.45 var(--ui)}
main th,main td{text-align:left;padding:7px 12px;border-bottom:1px solid var(--rule);vertical-align:top}
main th{font-weight:600}
main .callout{--c:var(--accent);padding:10px 16px;border-radius:10px;border-left:3px solid var(--c);background:color-mix(in srgb,var(--c) 9%,transparent);font-size:15px}
main .callout-tip{--c:var(--tip)}main .callout-warning{--c:var(--warning)}main .callout-important{--c:var(--important)}
main .callout>:last-child{margin-bottom:0}
main .callout-title{font:600 12px var(--ui);color:var(--c);margin-bottom:3px}
main .license{font:13px/1.55 var(--ui);color:var(--ink2);padding:14px 18px;border:1px solid var(--rule);border-radius:12px}
main .license h3{font:600 12.5px var(--ui);color:var(--ink);margin:12px 0 4px}
main .license p,main .license ul{margin:0 0 8px}
.topics{list-style:none;padding:0;display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:10px}
.topics a{display:block;padding:12px 14px;border-radius:12px;border:1px solid var(--rule);text-decoration:none;height:100%}
.topics strong{display:block;font:600 14.5px var(--ui);color:var(--accent);margin-bottom:2px}
.topics span{display:block;font:13px/1.45 var(--ui);color:var(--ink2)}
.pager{display:flex;justify-content:space-between;gap:12px;max-width:680px;margin-top:30px;padding-top:14px;border-top:1px solid var(--rule);font-size:13.5px}
.pager a{color:var(--accent);text-decoration:none}

"""
